### ISSUE TITLE
Fbe.octo is not aware of GitHub API quota

### ISSUE THREAD

**Issue by yegor256** [zerocracy/fbe#37]
Time to time, `Fbe.octo` operations fail due to quota overuse. I'm getting something like this:

```
Accessing GitHub API with a token (40 chars)
Octokit::Client.repository(728758275) in 5m10s
Octokit::TooManyRequests: GET https://api.github.com/repositories/728758275: 403 - API rate limit exceeded for user ID 526301. If you reach out to GitHub Support for help, please include the request ID 98C2:308015:6700B6:BADD51:66A330B1 and timestamp 2024-07-26 05:14:25 UTC. // See: https://docs.github.com/rest/overview/rate-limits-for-the-rest-api
	/app/vendor/bundle/ruby/3.2.0/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-1.10.3/lib/faraday/middleware.rb:19:in `block in call'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-1.10.3/lib/faraday/response.rb:61:in `on_complete'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-1.10.3/lib/faraday/middleware.rb:18:in `call'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-retry-1.0.3/lib/faraday/retry/middleware.rb:140:in `call'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:154:in `build_response'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-1.10.3/lib/faraday/connection.rb:516:in `run_request'
	/app/vendor/bundle/ruby/3.2.0/gems/faraday-1.10.3/lib/faraday/connection.rb:202:in `get'
	/app/vendor/bundle/ruby/3.2.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
	/app/vendor/bundle/ruby/3.2.0/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/app/vendor/bundle/ruby/3.2.0/gems/octokit-9.1.0/lib/octokit/connection.rb:19:in `get'
	/app/vendor/bundle/ruby/3.2.0/gems/octokit-9.1.0/lib/octokit/client/repositories.rb:27:in `repository'
	/app/vendor/bundle/ruby/3.2.0/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/app/vendor/bundle/ruby/3.2.0/gems/fbe-0.0.27/lib/fbe/octo.rb:105:in `repo_name_by_id'
	/app/vendor/bundle/ruby/3.2.0/gems/fbe-0.0.27/lib/fbe/issue.rb:28:in `issue'
```

Let's make it quota-aware. Let's check the quota via `rate_limit.remaining` every, say, 100 requests. If we are getting close to zero, we simply make a pause of, say, 60 seconds.

In order to implement this, I believe, we should create a new Faraday "middleware".

**Comment by Suban05** [comment]
@yegor256 can you assign me?

**Comment by yegor256** [comment]
@Suban05 sure, please go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.33`
