### ISSUE TITLE
undefined method `pull_request' for nil

### ISSUE THREAD

**Issue by yegor256** [zerocracy/fbe#78]
I see this [here](https://github.com/zerocracy/judges-action/actions/runs/10494241071/job/29070051712):

```
NoMethodError: undefined method `pull_request' for nil
	/usr/local/bundle/gems/fbe-0.0.57/lib/fbe/github_graph.rb:85:in `resolved_conversations'
	/action/judges/github-events/github-events.rb:95:in `comments_info'
	/action/judges/github-events/github-events.rb:189:in `fill_up_event'
	/action/judges/github-events/github-events.rb:318:in `block (4 levels) in <top (required)>'

```

**Comment by Suban05** [comment]
@yegor256 assign me, please

**Comment by yegor256** [comment]
@Suban05 go ahead!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.58`
